name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
jobs:
  create-test-case:
    runs-on: ubuntu-latest
    steps:
      # Install node and yarn
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
      - run: npm install -g yarn@1.22.5

      - name: Install Apt dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y moreutils

      # Create a yarn berry project
      - run: yarn init -2

      - run: cat package.json | jq '.workspaces=["frontend"] | .devDependencies.typescript="=4.4.4" | .name="@onboarding/root"' | sponge package.json

      - name: Create typescript files
        run: |
          echo '{"compilerOptions":{"incremental":true,"target":"es2019","module":"commonjs","lib":["esnext","es2020","es2019","dom"],"allowJs":false,"checkJs":false,"jsx":"react-jsx","declaration":true,"composite":true,"declarationMap":true,"sourceMap":true,"strict":true,"skipLibCheck":true,"noUnusedLocals":true,"noImplicitReturns":true,"noFallthroughCasesInSwitch":true,"moduleResolution":"node","baseUrl":".","types":[],"typeRoots":["@types","node_modules/@types"],"esModuleInterop":true,"resolveJsonModule":true,"forceConsistentCasingInFileNames":true}}' | jq > tsconfig.base.json
          echo '{}' | jq '.extends="./tsconfig.base.json" | .include=[] | .files=[] | .references=[{"path": "frontend"}]' > tsconfig.json

      - name: Create a snowpack app
        run: yarn create snowpack-app frontend --template @snowpack/app-template-react-typescript --use-yarn --no-install --no-git

      - name: Modify the generated files a touch
        run: |
          cat frontend/tsconfig.json | yarn dlx --quiet strip-json-comments-cli | jq '.extends="../tsconfig.base.json" | .compilerOptions.noEmit=false' | sponge frontend/tsconfig.json
          cat frontend/package.json | yarn dlx --quiet strip-json-comments-cli | jq '.name="@onboarding/frontend" | .devDependencies.typescript="=4.4.4"' | sponge frontend/package.json

      - name: Install pnpify and all yarn deps
        run: yarn workspace @onboarding/frontend add -D @yarnpkg/pnpify

      - name: Set workspaceRoot in the snowpack config file
        run: |
          sed -i 's/export default {/export default { workspaceRoot: "..",/' frontend/snowpack.config.mjs

      - name: Have the frontend use the react-syntax-highlighter component
        run: |
          yarn workspace @onboarding/frontend add react-syntax-highlighter
          yarn workspace @onboarding/frontend add -D @types/react-syntax-highlighter

          rm frontend/src/App.tsx
          cat <<EOT >> frontend/src/App.tsx
          import React from 'react';

          import SyntaxHighlighter from 'react-syntax-highlighter';
          import { docco } from 'react-syntax-highlighter/dist/esm/styles/hljs';

          function App() {
            return (
              <SyntaxHighlighter language="javascript" style={docco}>
                const a = 'foo';
                const b = [a, 'bar'];
              </SyntaxHighlighter>
            );
          }

          export default App;
          EOT

      - name: Build typescript
        run: yarn tsc --build --verbose

      - name: Start up the server
        run: yarn workspace @onboarding/frontend start --open none &

      - name: Test that we can talk to the server
        run: |
          sleep 800
          readonly status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/)
          if [ "$status_code" = "200" ]; then
              echo "Server queried successfully"
          else
              echo "Found invalid status code $status_code"
              exit 1
          fi
